version: "3.6"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=cookie
    ports:
    - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
